CREATE TABLE IF NOT EXISTS orders (
  id  BIGSERIAL PRIMARY KEY,
  number VARCHAR(150) UNIQUE NOT NULL,
  status VARCHAR(50) NOT NULL,
  user_id BIGINT REFERENCES users(id)  NOT NULL,
  accrual NUMERIC(15,2) DEFAULT 0,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);