CREATE TABLE IF NOT EXISTS users (
  id  BIGSERIAL PRIMARY KEY,
  login VARCHAR(150) UNIQUE NOT NULL,
  password VARCHAR NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_login_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);